import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Auth0Provider } from '@auth0/nextjs-auth0/client';
import "./globals.css";
import { Toaster } from "react-hot-toast";
import HeaderLayout from "@/components/uiComponents/HeaderLayout";
import FooterLayout from "@/components/uiComponents/FooterLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FinEd",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.jpg',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Auth0Provider>
        <body
          // className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
        >
          <HeaderLayout />
          {children}
          <FooterLayout />
          <Toaster />
        </body>
      </Auth0Provider>
    </html>
  );
}
